### ISSUE TITLE
Create a todo app demo

### ISSUE THREAD

**Issue by matoval** [SpiderGo-web/SpiderGo#6]
Create a todo app demo to show off spiderGo's functionality and benefits

- [ ] - Have ability to add an item to list of todos
- [ ] - Have ability to remove an item to list of todos 
- [ ] - Have ability to edit an item from todo list
- [ ] - Have ability to check off item from todo list
